-- util.AddNetworkString("ClothingStorageSystem.OpenAddItemMenu")
-- util.AddNetworkString("ClothingStorageSystem.SendToServerAddFile")
-- util.AddNetworkString("ClothingStorageSystem.OpenStorageMenu")
-- util.AddNetworkString("ClothingStorageSystem.EntitySpawner")